config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
    resources :comments
  end

  root 'posts#index'
  get '/about', to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :name, presence:true ,length: {minimum: 3, maximum: 50 }
  validates :body, presence:true ,length: {minimum: 3}
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many  :comments, dependent: :destroy
  validates :title, presence:true ,length: {minimum: 3, maximum: 50 }
  validates :body, presence:true,length: {minimum: 3}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post=Post.find(params[:post_id])
    @comment=@post.comments.create(params[:comment].permit(:name, :body))
    redirect_to post_path(@post, errors: @comment.errors.messages)
  end

  def edit
    @post=Post.find(params[:post_id])
    @comment=Comment.find(params[:id])
  end

  def update
    @post=Post.find(params[:post_id])
    @comment=@post.comments.find(params[:id])
    if @comment.update(params[:comment].permit(:name, :body))
      redirect_to @comment.post if @comment.save
    else
      redirect_to :back
    end
  end

  def destroy
    @post=Post.find(params[:post_id])
    @comment=@post.comments.find(params[:id])
    @comment.destroy
    redirect_to :back
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except:  [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post=Post.find(params[:id])
    @comment = Comment.new

    if params[:errors]
      params[:errors].each do |name, message|
        message.each do |msg|
          @comment.errors.add(name.to_sym, msg)
        end
      end
    end
  end

  def new
    @post=Post.new
  end

  def edit
    @post=Post.find(params[:id])
  end

  def update
   @post=Post.find(params[:id])

   if @post.update(params[:post].permit(:title, :body))
    redirect_to @post
   else
   render 'edit'
   end
  end
  def destroy
    @post=Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  def create
    @post= Post.new(post_params)
    if @post.save
    redirect_to @post
    else
    render 'new'
    end
  end
  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><%=comment.name%></p>
    <p class="comment_body"><%=comment.body%></p>
    <p class="comment_time">
    <%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>
  <%if user_signed_in? %>
  <p>
  <%=link_to "Delete",[comment.post, comment],
              method: :delete,
              class:"button",
              data:{ confirm: 'Are You Sure ?'}%>
  </p>
  <%end%>
</div>

app/views/comments/_form.html.erb
<%= form_for ([@post,@comment]) do |f| %>
  <%if @comment.errors.any?%>
    <div id="errors">
      <h2> <%= pluralize(@comment.errors.count, "error")%> prevented this comment from saving.</h2>
        <ul>
          <% @comment.errors.full_messages.each do|msg| %>
            <li> <%= msg %></li>
          <%end%>
        </ul>
    </div>
  <% end %>
 <p><%= f.label :name %><br>
    <%= f.text_field:name %></p>
  <p><%= f.label :body %><br>
     <%= f.text_area:body %></p>
  <p><%= f.submit %><br></p>
<%end%>

app/views/comments/edit.html.erb
<%= form_for [@post, @comment] do |f| %>
 <p><%= f.label :name %><br>
    <%= f.text_field:name %></p>
  <p><%= f.label :body %><br>
     <%= f.text_area:body %></p>
  <p><%= f.submit %><br></p>
<%end%>

app/views/layouts/_sidebar.html.erb
  <div id="sidebar">
    <div id="logo", class = "logo">
      <%= link_to root_path do%>
        <%= image_tag "favicon.ico"%>
      <%end%>
    </div>
    <ul>
      <li class ="category">Website</li>
      <li><%= link_to 'Blog',root_path %></li>
      <li><%= link_to 'About',about_path %></li>
    </ul>
    <ul>
      <li class="category">Social</li>
      <li><a href="https://www.facebook.com/abhinavcool016">Facebook</a></li>
      <li><a href="https://twitter.com/abhinavcool016">Twitter</a></li>
      <li><a href="https://www.instagram.com/_20abhinav/">Instagram</a></li>
      <li><a href="https://plus.google.com/+Abhinavgarg098">Google+</a></li>
      <li><a href="mailto:abhinav@prepsmarter.com">Email</a></li>
    </ul>
  <%if !user_signed_in? %>
   <p class="sign_in"><%= link_to "Admin Login", new_user_session_path %></p>
  <%end%>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/sidebar'%>
  <div id="main_content">
    <div id="header">
      <%if current_page?(root_path)%>
        <%= link_to "All Posts", root_path %>
        <%elsif current_page?(about_path)%>
          <p>About</p>
          <%else%>
            <%=link_to "Back to All Posts", root_path %>
      <%end%>
      <div class="buttons">
        <button class="button">
          <%= link_to "New Post",new_post_path %>
        </button>
        </div>
      <%if user_signed_in? %>
      <div class="buttons">
        <button class="button"><%= link_to "Logout",   destroy_user_session_path, method: :delete %></button>
      </div>
      <%end%>
    </div>
    <%flash.each do |name,msg| %>
    <%= content_tag(:div, msg, class: "alert")%>
    <%end%>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
<h1>Abhinav Garg</h1>
<h3>Software Developer at PrepSmarter, Inc.</h3>
<p>
• Highly focused, results-and goal-oriented as a member of the development team in the Information Technology with focus in the areas of technical support,  operations & development.
</p>
<p>
• Technical, Analytical, Presentation, Communication and Leadership skills. Strong team player and ability to perform in both team and individual settings.
</p>
<p>

• Quick learner and excellent team player having ability to meet tight deadlines and work under pressure.
</p>
<p>
• Excellent Inter personal and communication skills.
</p>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f|%>
  <%if @post.errors.any?%>
    <div id="errors">
      <h2> <%= pluralize(@post.errors.count, "error")%> prevented this post from saving.</h2>
        <ul>
          <% @post.errors.full_messages.each do|msg| %>
            <li> <%= msg %></li>
          <%end%>
        </ul>
    </div>
  <% end %>
  <p><%= f.label :title %><br><%= f.text_field:title %></p>
  <p><%= f.label :body %><br><%= f.text_area:body %></p>
  <p><%= f.submit %><br></p>
<%end%>

app/views/posts/_post.html.erb
<div class="post-wrapper">
  <h2 class="title"><%= link_to post.title, post %></h2>
  <h4 class="date"><%= post.created_at.strftime ("%B,%d, %Y")%></h4>
</div>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h2>Edit Post</h2>
  <%= render 'form'%>
</div>

app/views/posts/index.html.erb
<%= render @posts %>

app/views/posts/new.html.erb
<div id="page_wrapper">

<h2>New Post</h2>

<%= render 'form'%>

</div>

app/views/posts/show.html.erb
<div id="post_content">
<h2><%= @post.title %></h2>
<p class="body"><%= @post.body%></p>
<p class="date"> Submitted <%= time_ago_in_words(@post.created_at) %> ago
<%if user_signed_in? %>
| <%= link_to "Edit", edit_post_path(@post)%> | <%= link_to "Delete", @post,method: :delete, data:{ confirm: 'Are You Sure ?'}%>
</p>
<%end%>
  <div id="comments">
    <h2><%=@post.comments.count %> Comments</h2>
    <%= render @post.comments%>

    <h3>Add a comment: </h3>
    <%=render 'comments/form' %>
   </div>
</div>